'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkInsert('People', [{
        name: 'John Doe',
        isBetaMember: false
      }], {});
    */
    return queryInterface.bulkInsert('Reviews', [
      { albumId: 1, userId: 3, content: "On their new album, the artist turns their steady gaze towards the wreckage of the last few years and still finds a way to prioritize compassion.", createdAt: '2019-04-12', updatedAt: '2019-04-12' },
      { albumId: 2, userId: 1, content: "This album is, at its heart, an album about the freedom afforded by the open road. But where world' music's stuck on back roads, this album speeds down the interstate.", createdAt: '2012-01-12', updatedAt: '2012-01-12' },
      { albumId: 3, userId: 2, content: "The songwriter's new album interrogates what it means for their self-image to be centered on their art, while grappling with the way capitalist forces threaten to mute its radical possibilities.", createdAt: '2019-05-21', updatedAt: '2019-05-21' },
      { albumId: 4, userId: 4, content: "On the largely wordless everything perfect is already here, the composer lets us experience the world through their ears with field recordings, strings and a little tenderness.", createdAt: '2022-01-17', updatedAt: '2022-01-17' },
      { albumId: 5, userId: 1, content: "Their fifth studio album is ambitious to a fault, delivers introspective meditations over eclectic, but warm, productions.", createdAt: '2020-10-11', updatedAt: '2020-10-11' },
      { albumId: 6, userId: 3, content: "Flows brilliantly, great use of harmony, the melody trades off, the cadence trades off, the rhythm flows brilliantly, key signatures trade off, dynamics really flow together nicely, different instruments ebb and flow, the progression of this wonderful piece trades off, and basically all aspects of it flow together brilliantly.", createdAt: '2017-03-16', updatedAt: '2017-03-16' },
      { albumId: 3, userId: 13, content: "If music was food, this song would be five warm pounds of smoked bacon cooked just right in a pan of maple syrup that was extracted from a fresh, budding young pine in the glen. And, on the topic of maple syrup, this piece slowly oozes from the tuba's noise hole like sweet, savory molasses. The way the different melody lines flow together seamlessly offer up a decadence of grace that can be experienced by all five senses. Once I listened to this song, it inspired me to forever be a better person. I copied onto a CD and played it in my car as I drove halfway across the country to give my grandma a hug.", createdAt: '2017-06-15', updatedAt: '2017-06-15' },
      { albumId: 5, userId: 2, content: "It has become exceedingly difficult not to feast on this song's fruits as though you are a prisoner on death row eating your last meal. This piece just has so much to offer in terms of musical diversity! The underlying minor descending triads interweave of air of ominous mystery into an otherwise upbeat piece, and it's always pulling the listener one way or another between the different musical moods. Fantastic!", createdAt: '2017-06-27', updatedAt: '2017-06-27' },
      { albumId: 8, userId: 6, content: "The world renowned Plato once stated that 'Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything.' I ask the reader to keep in mind that Plato lived in time when the word 'gaiety' meant happiness and carefree-ness. And correct he was, for when I listened to this piece, my mind just sprouted wings and flew to new levels of mathematical and conceptual understanding previously unknown to man.", createdAt: '2017-08-30', updatedAt: '2017-08-30' },
      { albumId: 2, userId: 12, content: "From the very moment that humans have walked this earth to the moment you are reading this, man has made so many great contributions to society. William G. Allen gave us the allen wrench and hex key screw. Stephen Poplawski gave us the blender. Oh, it flows so nicely. And the way the instruments trade off is so fluid, it basically flows brilliantly. What else can I talk about that flows? Oh yes! The rhythm! The flow of the rhythym is so, so graceful!", createdAt: '2017-09-19', updatedAt: '2017-09-19' },
      { albumId: 4, userId: 15, content: "After listening to this beautiful, flowing piece, who's melody danced daintily across my eardrums like the ballerina of music, I saw everything differently. This piece finally opened my eyes to the reality of this world, and that reality is that everything is a piano. A chair is not a chair, it's just a piano with the legs closer together and no keys, with a very low build. Mr. Green is not a person, he is just a piano that's just missing two legs and is able to speak.", createdAt: '2017-11-09', updatedAt: '2017-11-09' },
      { albumId: 15, userId: 11, content: "My friends always boast about the cool stuff they've done. One of them has met the ambassador from South Sudan. One of them has gotten their violin signed by the grandson of Stradivarius. Finally, I can also chime in and boast of something great that happened to me. Last night, I listened to this piece 58 times in a row. The melody flowed brilliantly all 58 times. I was impressed that the composer used cadences in such a graceful, fluent manner, while keeping the melody choppy and fast.", createdAt: '2018-01-15', updatedAt: '2018-01-15' },
      { albumId: 11, userId: 13, content: "Listen to this piece?? Ha! I would derive far greater pleasure from falling into an industrial sized wood chipper, climbing out halfway while barely hanging on to my life, and then falling back in again. The horror of this scenario pales in comparison to this awful monstrosity that some have the nerve to call music. This piece does not flow at all, no melody trades off, and there is no general flow. Frankly, I am amazed that I even have to review this piece, because typing this review out is not worth the energy required to move my fingers.", createdAt: '2018-02-02', updatedAt: '2018-02-02' },
      { albumId: 8, userId: 5, content: "It's hard to make anything sound good when played on the chromatic bagpipe, and though I usually despise the chromatic bagpipe and bash on it out of pure spite as often as I possibly can in my reviews, I have to admit, this piece is quite an ear-pleaser. The way it flows is pretty much unparalleled, and I have great admiration for the skill required by the composer to offer such wonders to his loyal fans.", createdAt: '2019-04-12', updatedAt: '2019-04-12' },
      { albumId: 12, userId: 9, content: "Upon hearing this intriguing delight, I experienced the same sort of happy, childish surprise that overcomes you when you find three hundred dollars laying on the ground in one of those sketchy alleys in New York City in which old men play chess. At first it started off slow and boring, but as the piece progressed, more complexity appeared, and stimulated my brain both intellectually and emotionally. I'm sure you have, at one point, heard somebody refer to a deep, intellectual quote as food for thought.", createdAt: '2019-04-12', updatedAt: '2019-04-12' },
      { albumId: 7, userId: 7, content: "The only solace I find in the fact that Mozart has been long dead is that he never lived to see a time in history when this was considered a good song, and even now I hope he is not rolling around in his grave! If you were to take a shovel and dig through the metaphorical pit of human depravity to the very bottom, the written manuscript of this piece would be staring back up at you in all it's wretchedness. Not only were there so many repeated deceptive cadences, but the dissonance present from beginning to end while listening to this made me wish I was like Helen Keller - deaf.", createdAt: '2018-04-25', updatedAt: '2018-04-25' },
      { albumId: 9, userId: 3, content: "This work of art can only be the sonic brainchild of a supernatural mind, and the only thing worthy of shame here is that it has not been added as the eighth wonder of the world. When comparing all music from the beginning of time to the present, this is definitely the cream of the crop. It's hard to determine where to start when analyzing so much ingenuity, but with a song of such epic proportions of listening pleasure, it is only fitting to start with the melody. ", createdAt: '2018-05-06', updatedAt: '2018-05-06' },
      { albumId: 6, userId: 15, content: "When I hear this beautiful tune of arpeggios going up and down, I feel as though I am being uplifted by angels, dropped, and lifted again, like a heavenly game of angel hot potato. It's also impossible to indulge in this harmony without salivating at the complexity of chords. The structure of chords is so structural, and the harmony is so harmonic, it paralyzes me with wonder that one human man could give birth to a piece of such epic proportions. The composer utilizes the chosen instruments in the same veteran manner that an 80 year old plumber would utilize his plunger on a beautiful porcelain toilet.", createdAt: '2018-10-05', updatedAt: '2018-10-05' },
      { albumId: 5, userId: 14, content: "The difference between this piece and a toilet, however, is that this piece doesn't have a clogging effect that most toilets and modern day sounds of life have on the human thought process. It gracefully flows, and opens up the mind to a level of understanding that cannot be attained by any other means. If somebody asked me to rate this piece on a scale of 1-27, I would, without hesitating, give it a 27.5, and justifiably so!!", createdAt: '2021-06-19', updatedAt: '2021-06-19' },
      { albumId: 10, userId: 12, content: "The composer tries to emulate greats like Beethoven by being bold with deceptive cadence, sustains that are carried over the course of the chords, and tones that are so contrasted the whole piece so that a keyboardist would need to be born with unusually large arms just to reach the polarized notation simultaneously. We are all fans of music before genre, and other genres must be respected even if not enjoyed, but I will sink in quicksand and die before referring to this garbage as music of any genre. Either my ears cannot discern the difference between intervals (most likely impossible), or I thought I heard a chord that was the likes of 13 minor seconds stacked chronologically on top of each other.", createdAt: '2022-02-02', updatedAt: '2022-02-02' },
      { albumId: 13, userId: 13, content: "This is an overload of tones which completely abandons the point of a key signature, and ruins the cadence altogether as it cannot possibly be resolved. Do you know what else cannot possibly be resolved?? My epic disgust at this piece!", createdAt: '2019-04-12', updatedAt: '2019-04-12' },
      { albumId: 14, userId: 8, content: "The prognosticated perfect cadences implied by the sustained tonic on the first inversion actually go plagal on us all, and the fifth all of a sudden becomes the fourth as the piece advances one key up from where it started. Brilliant! Other than that, I can't get over the way that the harmony to this piece is syncopated between the melody line, which allows both harmony and melody to become a flurry of overwhelming tones that outlast the beauty of the piece itself and give it a quality of undying longevity, even though it is relatively short. Stupendous! ", createdAt: '2022-05-14', updatedAt: '2022-05-14' },
      { albumId: 15, userId: 11, content: "Eh. And by 'eh', I mean that this is the most grotesque abomination that has ever stricken this world. It has unduly left a black mark upon society, and the only hope for mankind is to completely obliterate every trace of this horrendous abomination, and kill those who have heard it so it cannot possibly be replicated for as long into the foreseeable future as possible. Firstly, let's distinguish two different things. There are pieces that, musically, think outside the box, and create new and memorable experiences for the listener. Then there are pieces that are so far out of the box that, in essence, they just become idiotic and absurd. A burden to listen to. ", createdAt: '2022-05-30', updatedAt: '2022-05-30' },
      { albumId: 11, userId: 9, content: "This piece is of the latter category, and even that might be complimenting it to much. Let's start off to say that the moldy, stinking melody doesn't even flow. And that wouldn't usually be a problem, but nothing flows!! Not the stale harmony, the moisture-infested rhythm, or the fungus-covered Cantus Firmus. If this piece were a disease, it would be a strain of leprosy that somehow bonded with ebola. And there I go giving it too much credit for what it's actually worth again. It sounds as if a whole slew of songwriters were brought into their little cubicle farm to crank out a song to spoonfeed to the masses, like most music is written nowadays, and they just synced up their musescores and started going note happy like there was no tomorrow, without any regard to what any of their peers were writing.", createdAt: '2021-06-19', updatedAt: '2021-06-19' },
      { albumId: 7, userId: 7, content: "If you took some bad pieces, and sort-of mashed them all into one, that would be this piece. A failure. Failure. Whoever posted this piece, I suggest you transfer schools, because if I see you again I will end your life.", createdAt: '2020-03-14', updatedAt: '2020-03-142' },
      { albumId: 1, userId: 6, content: "The melody flowed brilliantly all 58 times. I was impressed that the composer used cadences in such a graceful, fluent manner, while keeping the melody choppy and fast. I was impressed by the way the deceptive cadence took this piece down a whole different path than expected. I was impressed that that the two lines of melody overlapped each other to make it sound like an echoing, angelic war call of bliss. Heck, I was impressed by almost everything about this piece. From the flowing melody to the harmony that flows, everything trades off so nicely. The choice of instrumentation was flawless, it wouldn't have sounded better on anything else. Every time you listen, you discover something new about the piece. So far, I have discovered 58 new things about this amazing ear-pleaser, and I trust I will continue to learn new things when I listen to it later today. ", createdAt: '2020-10-22', updatedAt: '2020-10-22' },
      { albumId: 6, userId: 10, content: "There is obvious evidence of textural reduction, species counterpoint, dimensional strangulation, and sub-diatonic reimplementation. My God! Thank high heaven above that this piece is out of range of the chromatic bagpipe! I could not bear to hear a rendition of this on such a disgraceful instrument! In an era when the production of music is not so much creative as it is spoonfeeding greasy formulaic techno trash in to the mouths of the masses in order to turn a profit, people need to come back and listen to music like this!", createdAt: '2019-04-12', updatedAt: '2019-04-12' },
      { albumId: 5, userId: 4, content: "Every element of theory was present in this piece from the beginning to the end! There were whole notes, and definitely half notes as well. The variety even went deeper. If you don't listen to this, you are probably a loser, because this song is worth the full listen, even if it is 92 minutes long. Would I recommend to a friend? Heck, I would recommend this to the wife of Vladimir Putin's son!", createdAt: '2018-02-02', updatedAt: '2018-02-02' },
      { albumId: 3, userId: 5, content: "I feel like this also matched the main motive progression, so it didn't sound out of place. I have to give the performer an A+ for a great performance. Even though there was a slip on the 342nd note, and the 56th cadence did not conform to the expected dynamic, those were the only two mistakes. But really, this larger-than-life opus of the gods means something more to me, something greater than any other piece I have ever listened to. This deserves my ultimate applause! When my third cousin twice removed visits this weekend, I will definitely recommend it to him!", createdAt: '2019-08-30', updatedAt: '2019-08-30' },
      { albumId: 15, userId: 2, content: "The theory behind this reasoning is that, since classical music is very structural and follows a steady meter, the child, if not killed first, will come out with increased spacial, mathematical, and organizational perception than, persay, a child who had been listening to a heavy suicide funk pop glam death metal band. Anyway, as I was saying, I experienced this mental development first hand. As I was listening, I all of a sudden understood how quantum physics works, and, while sitting at my desk listening to this piece, I was able to engineer a particle collider that could reduce the temperature inside to absolute zero, making it possible to collide particles without the slightest inhibition of friction. Anyhow, back to the piece.", createdAt: '2020-03-14', updatedAt: '2020-03-14' },
      { albumId: 11, userId: 3, content: "As I was listening, I all of a sudden understood how quantum physics works, and, while sitting at my desk listening to this piece, I was able to engineer a particle collider that could reduce the temperature inside to absolute zero, making it possible to collide particles without the slightest inhibition of friction. Anyhow, back to the piece. What a find most interesting about this piece is that the composer was born into a time when music was evolving into a new generation, so his life was caught between two conflicting styles of music. But the thing about this piece is that both styles seemingly influenced the piece equally, one no more than the other, and the final product was a brilliant mix which would actually be able to cater to a much wider base of music consumers than before. Sonic brilliance, or devious marketing strategy?? It's up to you to decide. Nevertheless, the quality is very much above par of what you'd expect from a typical work of this time. Although the cadences are very traditional and don't differ much within the piece, the species counterpoint works like a design around a foundational bass line filled with vibrant, unforgiving timbre.", createdAt: '2021-03-20', updatedAt: '2021-03-20' },
      { albumId: 13, userId: 1, content: "I liked the way that he stuck to the integrity of the piece without changing it much, but being more creative in the way of variations on a theme. There seems to be a double-motif in this piece, one motif is not exploited more than the other so it's hard to tell which was the intended foundation for the melody, but they work in an antecedent-precedent manner that really ties it all together, and the end was really cool when they were both switching off, one low and one high. Don't believe it when people say that the composer was high on a fat pound of grass when he composed this. That was an urban legend that spawned in the nineties because of a popular movie that attempted to redefine the creation of the song. Overall, I much appreciated the listen. It reminded me of a Beethoven style, but was more easy to listen to and would probably be really fun to play.", createdAt: '2021-06-28', updatedAt: '2021-06-28' },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Reviews', null, {});
  }
};
